spring:
  application:
    name: yue-ai-agent
  ai:
    dashscope:
      api-key: sk-97a7c0d0571042eab71be6d1a4de16f9
      chat:
        options:
          model: qwen-plus-latest

server:
  port: 8123
  servlet:
    context-path: /api

# springdoc-openapi??????
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.yue.yueaiagent.controller
# knife4j???????????????
knife4j:
  enable: true
  setting:
    language: zh_cn

# searchAPI
search-api:
  api-key: ZK3WVStByiCHPV9cwnnWo6FS
# 修改日志级别，查看 Spring AI 更多调用细节
logging:
  level:
    org.springframework.ai: DEBUG